# Spring Boot
springBootVersion=3.4.13

# Quality tools
spotlessVersion=8.2.1
errorProneVersion=5.0.0
errorProneCoreVersion=2.45.0

# OpenAPI Generator
openApiGeneratorVersion=7.19.0

# Jib
jibVersion=3.5.2

# TestContainers
testcontainersVersion=1.21.4

# springdoc
springdocVersion=2.8.14

# jackson-databind-nullable
jacksonDatabindNullableVersion=0.2.8

# Lombok
lombokVersion=1.18.42

# Resilience4j
resilience4jVersion=2.2.0
