spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/video_service
    username: video_service
    password: local_dev

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
