spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/video_service
    username: video_service
    password: local_dev
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/devdata
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/.well-known/jwks.json
  cloud:
    aws:
      sqs:
        endpoint: http://localhost:4566

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
